// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZZEAYsCLUn6SAaIuVavWzRGXY9YOOZbs',
    appId: '1:975657109570:web:0dda629d9c1a7bea0545db',
    messagingSenderId: '975657109570',
    projectId: 'eventium-74c4c',
    authDomain: 'eventium-74c4c.firebaseapp.com',
    storageBucket: 'eventium-74c4c.firebasestorage.app',
    measurementId: 'G-18KM8HNTYJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCje7EUV8OF80bFfxECVsz4L8G27pghuR8',
    appId: '1:975657109570:android:729fbef90768a9da0545db',
    messagingSenderId: '975657109570',
    projectId: 'eventium-74c4c',
    storageBucket: 'eventium-74c4c.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZZEAYsCLUn6SAaIuVavWzRGXY9YOOZbs',
    appId: '1:975657109570:web:0dda629d9c1a7bea0545db',
    messagingSenderId: '975657109570',
    projectId: 'eventium-74c4c',
    authDomain: 'eventium-74c4c.firebaseapp.com',
    storageBucket: 'eventium-74c4c.firebasestorage.app',
    measurementId: 'G-18KM8HNTYJ',
  );

}